using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using StarterApp.Data;
using StarterApp.DTOs;
using StarterApp.Exceptions;
using StarterApp.Models;

namespace StarterApp.Services;

public class AuthService : IAuthService
{
    private readonly ApplicationDbContext _context;
    private readonly IPasswordHasher<User> _passwordHasher;
    private readonly ILogger<AuthService> _logger;

    public AuthService(ApplicationDbContext context, IPasswordHasher<User> passwordHasher, ILogger<AuthService> logger)
    {
        _context = context;
        _passwordHasher = passwordHasher;
        _logger = logger;
    }

    public async Task<RegisterResponse> RegisterUserAsync(RegisterRequest request)
    {
        try
        {
            var userExists = await UserExistsAsync(request.Email, request.Email);
            if (userExists)
            {
                _logger.LogWarning("Registration attempt with existing email: {Email}", request.Email);
                throw new ConflictException("Email already exists");
            }

            var passwordHash = _passwordHasher.HashPassword(null!, request.Password);
            var user = new User
            {
                FirstName = request.FirstName,
                LastName = request.LastName,
                Email = request.Email,
                PasswordHash = passwordHash
                // Id, CreatedAt, UpdatedAt are auto-generated by database
            };

            _context.Users.Add(user);
            await _context.SaveChangesAsync();

            _logger.LogInformation("User {Email} registered successfully with ID {UserId}",
                user.Email, user.Id);

            return new RegisterResponse
            {
                Id = user.Id,
                Username = user.Username ?? string.Empty,
                Email = user.Email,
                FirstName = user.FirstName,
                LastName = user.LastName,
                CreatedAt = user.CreatedAt
            };
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error during user registration");
            throw;
        }
    }

    public async Task<bool> UserExistsAsync(string username, string email)
    {
        return await _context.Users
            .AnyAsync(u => u.Email.ToLower() == email.ToLower() ||
                          (u.Username != null && u.Username.ToLower() == username.ToLower()));
    }
}
